### ISSUE TITLE
Switch from rustc-serialize dependency to serde

### ISSUE THREAD

**Issue by SnirkImmington** [way-cooler/way-cooler#181]
Choo choo! The hype train is hyping its way to `serde`. All aboard! Hype hype! 🚂 🚋 🚋 🚋 🚋 

In completing #178 (yaml configs) and #174 (remove `registry`) we can drop our `rustc_serialize` dependency and switch to the newer `serde`.

`rustc-serialize` support has been dropped because it's not hype enough and is being replaced with `serde`. Being `v0.8` is so much more stable `v0.3`.

We only have a few usages that need to be switched over, as far as I can tell:
- [ ] We have JSON data in the registry - this will be dropped in #174
- [ ] We have Lua<->JSON converters + custom declaration macros - dropped in #174 + we can get a serde macros crate
- [ ] New config/theme format with yaml (from #178) can use `serde_yaml`, we can provide conversions to and from Lua if needed
- [ ] We can remove the `rustc_serialize` feature from the `uuid` dependency (not sure if we're using it) as we mostly need to/from string conversions

**Comment by Timidger** [comment]
I believe (though can't say for sure) that we were originally using the `rustc_serialize` feature of the `uuid` dependency in order to write it out when printing out the tree in json [here](https://github.com/Immington-Industries/way-cooler/blob/master/src/layout/mod.rs#L43). Although, that should be possible without it, so I'm actually not sure why that dependency is there (we're currently not using it)

**Comment by dtolnay** [comment]
The rustc-serialize crate has been deprecated ([announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay)) and Serde is stable ([announcement](https://github.com/serde-rs/serde/releases/tag/v1.0.0))!

**Comment by Timidger** [comment]
This is severely outdated, Way Cooler no longer requires a serialization library.
